services:
  pipeline1:
    build:
      context: ./pipeline-rtsp
    container_name: pipeline1-rtsp
    restart: unless-stopped
    ports:
      - "8554:8554"

  pipeline2:
    build:
      context: ./pipeline-rtsp-to-srt
    container_name: pipeline2-rtsp-to-srt
    restart: unless-stopped
    depends_on:
      - pipeline1
      - pipeline3

  pipeline3:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx-server
    restart: unless-stopped
    volumes:
      - ./server/mediamtx.yml:/mediamtx.yml
    ports:
      - "8888:8888" # SRT
      - "8889:8889" # WebRTC
      - "8080:8080" # HLS
      - "1935:1935" # RTMP

  ui:
    build:
      context: ./server/ui
    container_name: ui-hls-player
    restart: unless-stopped
    ports:
      - "8181:80"
    depends_on:
      - pipeline3