version: '3.8'
services:
  # Pipeline 1: MP4 → RTSP
  rtsp-server:
    build: ./pipeline-rtsp/rtsp_server
    ports:
      - "8554:8554"
    restart: unless-stopped
    networks:
      - pipeline-network

  # Pipeline 2: RTSP → SRT
  rtsp-to-srt:
    build: ./pipeline-rtsp-to-srt
    environment:
      - RTSP_URL=rtsp://rtsp-server:8554/cam1
      - SRT_URL=srt://media-server:9999?mode=caller
    restart: unless-stopped
    depends_on:
      - rtsp-server
    networks:
      - pipeline-network

networks:
  pipeline-network:
    driver: bridge
