version: '3.8'
services:
  # Pipeline 1: MP4 → RTSP
  rtsp-server:
    build: ./pipeline-rtsp/rtsp_server
    ports:
      - "8554:8554"
    restart: unless-stopped
    networks:
      - pipeline-network

  # Pipeline 2: RTSP → SRT (to MediaMTX)
  rtsp-to-srt:
    build: ./pipeline-rtsp-to-srt
    environment:
      - RTSP_URL=rtsp://rtsp-server:8554/cam1
      - SRT_URL=srt://media-server:8890?mode=caller&streamid=publish:live
    restart: unless-stopped
    depends_on:
      - rtsp-server
      - media-server
    networks:
      - pipeline-network

  # Pipeline 3: MediaMTX - Complete Streaming Server
  media-server:
    build: ./server/mediamtx
    ports:
      - "8555:8555"      # RTSP (different from Pipeline 1)
      - "8888:8888"      # HLS  
      - "8889:8889"      # WebRTC
      - "8890:8890/udp"  # SRT
      - "8002:8002/udp"  # WebRTC UDP
      - "8003:8003/tcp"  # WebRTC TCP
      - "9997:9997"      # API
      - "9998:9998"      # Metrics
    restart: unless-stopped
    networks:
      - pipeline-network

  # Pipeline Monitor Web UI
  pipeline-monitor:
    build: ./server/web
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    user: root
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    restart: unless-stopped
    depends_on:
      - rtsp-server
      - rtsp-to-srt
      - media-server
    networks:
      - pipeline-network

networks:
  pipeline-network:
    driver: bridge
